apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      resources:
        requests:
          memory: '512Mi'
          cpu: '300m'
        limits:
          memory: '1024Mi'
          cpu: '500m'
    - name: node
      image: node:18-alpine
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: '512Mi'
          cpu: '300m'
        limits:
          memory: '1024Mi'
          cpu: '1000m'
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      resources:
        requests:
          memory: '256Mi'
          cpu: '200m'
        limits:
          memory: '512Mi'
          cpu: '500m'
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: '512Mi'
          cpu: '300m'
        limits:
          memory: '1024Mi'
          cpu: '500m'
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
